/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_helloworld */

#ifndef _Included_jni_helloworld
#define _Included_jni_helloworld
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_jni_helloworld_disHelloWorld
  (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
